# Build the Go Binary.
FROM golang:1.17-alpine
ARG BUILD_REF
ARG BUILD_DATE

WORKDIR /service

# COPY go.mod ./
# COPY go.sum ./
# RUN go mod download -> no longer need to run as we have vendor

# Copy the source code into the container.
COPY . ./

RUN go build -ldflags "-X main.build=${BUILD_REF}"

CMD ["./go-service"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="service" \
      org.opencontainers.image.revision="${BUILD_REF}" \