# Put the database in its own namespace
apiVersion: v1
kind: Namespace
metadata:
  name: database-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-pod # name it database-pod in the database-system
  namespace: database-system
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: database
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: postgres
        image: postgres:14-alpine
        resources:
          limits:
            cpu: "1000m" # Up to 1 full core
          requests:
            cpu: "1000m" # Use 1 full core
        imagePullPolicy: Always
        env:
        - name: POSTGRES_PASSWORD # Need to set the password at the time the container executes
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_password
        - name: POSTGRES_USER # Need to set the user at the time the container executes
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_user
        ports:
        - name: postgres
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: database-system
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres     