apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-pod
  namespace: sales-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sales 
  template:
    metadata:
      labels:
        app: sales 
    spec:
      initContainers:
      # # sales-api init container configuration. Note Admin executable is built in dockerfile.
      # - name: init-migrate
      #   image: sales-api-image
      #   command: ['../../tooling/admin/admin'] # run the admin executable to migrate Database.
      containers:
      # sales-api container configuration
      - name: sales-api
        resources:
          limits:
            cpu: "2000m" # Up to 2 full cores
          requests:
            cpu: "1000m" # Use 1 full cores